### ISSUE TITLE
Extra Help

### ISSUE THREAD

**Issue by NerunSmarts** [Gabriel-H4/pihole#1]
you forgot to block this
https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO

**Comment by Gabriel-H4** [comment]
1. That is not an ad / spam URL / malware URL / etc, it is a YouTube video.
2. Come on Jonah, I'm not going to fall for it when you left the"channel=RickAstleyVEVO" referrer in the domain
